# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            SMPI<br> CourseWare
tagline:          'SMPI XX CourseWare'
description:      ''
baseurl:          /SMPI_CourseWare/

gems: [jekyll-paginate]

paginate:         5


