# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: pygments


# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            SMPI CourseWare
tagline:          'SMPI CourseWare'
description:      ''
baseurl:          /SMPI_CourseWare/



